# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 18:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=500)),
                ('subtitle', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=500)),
                ('link', models.URLField(default='/')),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 8, 2, 21, 32, 44, 829434))),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('link', models.URLField(default='/')),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='skytravel.City')),
            ],
        ),
    ]
