# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 08:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytravel', '0003_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.URLField(default='/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 29, 11, 24, 41, 21825)),
        ),
        migrations.AlterField(
            model_name='location',
            name='link',
            field=models.URLField(default='/'),
        ),
    ]
