# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 08:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytravel', '0004_auto_20170729_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 29, 11, 41, 48, 284499)),
        ),
    ]
