# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 11:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytravel', '0005_auto_20170729_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 30, 14, 54, 27, 238119)),
        ),
    ]
