# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 19:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytravel', '0008_auto_20170731_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 31, 22, 52, 41, 917848)),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='skytravel.City'),
        ),
    ]
