# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 20:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytravel', '0009_auto_20170731_2252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('pk',)},
        ),
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='location',
            name='slug',
            field=models.SlugField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 1, 23, 51, 14, 863295)),
        ),
    ]
