# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 20:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytravel', '0010_auto_20170801_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='location',
            name='slug',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 1, 23, 53, 22, 461769)),
        ),
    ]
