# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 18:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytravel', '0011_auto_20170801_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 2, 21, 28, 31, 393021)),
        ),
    ]
