# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 18:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytravel', '0012_auto_20170802_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 2, 21, 29, 33, 750520)),
        ),
    ]
