# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 08:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 29, 11, 18, 42, 931260)),
        ),
    ]
