# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 12:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20170731_2252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 1, 15, 15, 55, 8349)),
        ),
    ]
